.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2020 Baeldung <test@test.com>
.\"
.TH AESTOOL 1 
.SH NAME
aestool \- AES encryption/decryption tool
.SH SYNOPSIS
.B aestool [-e|-d] input-file output-file
.SH DESCRIPTION
.B aestool
encrypts or decrypts a file using the AES cipher.
.SH SEE ALSO
.BR gpg (1).
.SH AUTHORS
.B aestool
was written by 
David Harper <david@obliquity.net>
.PP
This document was written by David Harper <david@obliquity.net> for Debian.
